import turtle
turtle.numinput("hi","bye",1000,minval=1,maxval=1000)
turtle.textinput("hello","seeyou")

#turtle.onkeypress(f,"up")
turtle.listen()
d=turtle.Turtle()
turtle.bgcolor("black")
turtle.pencolor("gold")
turtle.pensize(3)
turtle.setpos(100,100)
turtle.setpos(50,100)
turtle.pencolor("white")
turtle.setx(100)
turtle.pencolor("blue")
turtle.setheading(45)
turtle.fd(100)
tup=(0.5,0.6,0.03)
turtle.pencolor(tup)
turtle.shape("triangle")
#turtle.shapesize(10)
turtle.fd(100)
#turtle.circle400)
#turtle.xcor(50)
turtle.degrees(400)
print(round(turtle.xcor(), 5))
turtle.done()